//
//  WelcomePresenter.swift
//  Authentication
//
//  Created by Raymond Law on 10/26/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomePresentationLogic
{
  func presentLogin(response: Welcome.Login.Response)
}

class WelcomePresenter: WelcomePresentationLogic
{
  weak var viewController: WelcomeDisplayLogic?
  
  // MARK: Login
  
  func presentLogin(response: Welcome.Login.Response)
  {
    let greeting = response.success ? "Hello \(response.username!)" : ""
    let viewModel = Welcome.Login.ViewModel(success: response.success, greeting: greeting)
    viewController?.displayLogin(viewModel: viewModel)
  }
}
