//
//  WelcomeWorker.swift
//  Authentication
//
//  Created by Raymond Law on 10/26/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class WelcomeWorker
{
  let user = (email: "ray@clean-swift.com", password: "secret", username: "Raymond")
  
  func login(email: String, password: String, completionHandler: @escaping (Bool, String?) -> Void)
  {
    if email == user.email && password == user.password {
      completionHandler(true, user.username)
    } else {
      completionHandler(false, nil)
    }
  }
}
