//
//  WelcomeModels.swift
//  Authentication
//
//  Created by Raymond Law on 10/26/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Welcome
{
  // MARK: Use cases
  
  enum Login
  {
    struct Request
    {
      var email: String
      var password: String
    }
    struct Response
    {
      var success: Bool
      var username: String?
    }
    struct ViewModel
    {
      var success: Bool
      var greeting: String
    }
  }
}
